# -*- coding: utf-8 -*-
"""
Created on Sat Jan 16 00:02:45 2016

@author: ORCHISAMA
"""
#Problem - 45

#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

#first find pentagonal number > T(145) as it is largest

import math

def findPentagonal(n):
    return n*(3*n - 1)/2

def quadratic(a,b,c):
    dis = b**2 - 4*a*c
    if dis < 0:
        return False
    else:
        root = (float(-b) + math.sqrt(dis))/(2*a)
        if root.is_integer():
            return True
        else:
            return False
    
def checkHex(n):
    a = 2
    b = -1
    c = -n
    return quadratic(a,b,c)
    
def checkTri(n):
    a = 1
    b = 1
    c = -2*n
    return quadratic(a,b,c)

cur = 166    
while(True):
    num = findPentagonal(cur)
    if checkHex(num) and checkTri(num):
        print cur,num
        break
    cur += 1


    
    
    